Add or pattern

diff --git a/.github/workflows/status_test.yaml b/.github/workflows/status_test.yaml
--- a/.github/workflows/status_test.yaml
+++ b/.github/workflows/status_test.yaml
@@ -11,7 +11,8 @@ jobs:
     #   github.event.state == 'error' ||
     #   github.event.state == 'failure'
     steps:
-      - run: exit 1
+      - run: sleep 1000
+        if: false
       - if: cancelled()
         run: echo 'cancelled'
       - if: failure()
@@ -30,3 +31,11 @@ jobs:
         run: echo 'cancelled && !failure'
       - if: ${{ success() }}
         run: echo 'success'
+      - if: cancelled() || failure()
+        run: echo 'cancelled || failure'
+      - if: ${{ !cancelled() || !failure() }}
+        run: echo '!cancelled || !failure'
+      - if: ${{ !cancelled() || failure() }}
+        run: echo '!cancelled || failure'
+      - if: ${{ cancelled() || !failure() }}
+        run: echo 'cancelled || !failure'
